# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from funcao import Fatiamento
fatiamento = Fatiamento()


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(404, 315)
        Form.setStyleSheet("background-color: rgb(85, 0, 127);")
        self.btn_add_valor = QtWidgets.QPushButton(Form)
        self.btn_add_valor.setGeometry(QtCore.QRect(280, 40, 101, 24))
        self.btn_add_valor.setStyleSheet("background-color: rgb(0, 163, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"text-align: center;\n"
"display: inline-block;\n"
"font-size: 12px;\n"
"box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);")
        self.btn_add_valor.setObjectName("btn_add_valor")
        self.ln_valor = QtWidgets.QLineEdit(Form)
        self.ln_valor.setGeometry(QtCore.QRect(10, 40, 113, 22))
        self.ln_valor.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(223, 223, 223);")
        self.ln_valor.setObjectName("ln_valor")
        self.ln_inicio = QtWidgets.QLineEdit(Form)
        self.ln_inicio.setGeometry(QtCore.QRect(130, 40, 51, 22))
        self.ln_inicio.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(223, 223, 223);")
        self.ln_inicio.setObjectName("ln_inicio")
        self.ln_fim = QtWidgets.QLineEdit(Form)
        self.ln_fim.setGeometry(QtCore.QRect(190, 40, 41, 22))
        self.ln_fim.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"color: rgb(223, 223, 223);")
        self.ln_fim.setObjectName("ln_fim")
        self.btn_processar = QtWidgets.QPushButton(Form)
        self.btn_processar.setGeometry(QtCore.QRect(280, 180, 101, 61))
        self.btn_processar.setStyleSheet("background-color: rgb(0, 163, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"text-align: center;\n"
"display: inline-block;\n"
"font-size: 12px;\n"
"box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/folder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_processar.setIcon(icon)
        self.btn_processar.setObjectName("btn_processar")
        self.msg_erro = QtWidgets.QLabel(Form)
        self.msg_erro.setGeometry(QtCore.QRect(10, 290, 381, 16))
        self.msg_erro.setStyleSheet("color: rgb(231, 0, 0);")
        self.msg_erro.setText("")
        self.msg_erro.setObjectName("msg_erro")
        self.btn_apagar_valor = QtWidgets.QPushButton(Form)
        self.btn_apagar_valor.setGeometry(QtCore.QRect(280, 70, 101, 24))
        self.btn_apagar_valor.setStyleSheet("background-color: rgb(0, 163, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"text-align: center;\n"
"display: inline-block;\n"
"font-size: 12px;\n"
"box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);")
        self.btn_apagar_valor.setObjectName("btn_apagar_valor")
        self.tv_valores = QtWidgets.QTableWidget(Form)
        self.tv_valores.setGeometry(QtCore.QRect(10, 80, 251, 192))
        self.tv_valores.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.tv_valores.setObjectName("tv_valores")
        self.tv_valores.setColumnCount(1)
        self.tv_valores.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Valores")
        self.tv_valores.setHorizontalHeaderItem(0, item)
        self.btn_apagar_valores = QtWidgets.QPushButton(Form)
        self.btn_apagar_valores.setGeometry(QtCore.QRect(280, 120, 101, 24))
        self.btn_apagar_valores.setStyleSheet("background-color: rgb(0, 163, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"text-align: center;\n"
"display: inline-block;\n"
"font-size: 12px;\n"
"box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);")
        self.btn_apagar_valores.setObjectName("btn_apagar_valores")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(270, 160, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(270, 110, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(270, 30, 118, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(270, 40, 3, 61))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(390, 40, 3, 61))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(270, 260, 118, 3))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(380, 170, 16, 81))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Form)
        self.line_9.setGeometry(QtCore.QRect(260, 170, 20, 81))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_9.raise_()
        self.btn_add_valor.raise_()
        self.ln_valor.raise_()
        self.ln_inicio.raise_()
        self.ln_fim.raise_()
        self.btn_processar.raise_()
        self.msg_erro.raise_()
        self.btn_apagar_valor.raise_()
        self.tv_valores.raise_()
        self.btn_apagar_valores.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_8.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.ln_valor, self.ln_inicio)
        Form.setTabOrder(self.ln_inicio, self.ln_fim)
        Form.setTabOrder(self.ln_fim, self.btn_add_valor)
        Form.setTabOrder(self.btn_add_valor, self.btn_processar)
        Form.setTabOrder(self.btn_processar, self.btn_apagar_valor)
        Form.setTabOrder(self.btn_apagar_valor, self.tv_valores)

        self.btn_add_valor.clicked.connect(self.cad_valor)
        self.btn_processar.clicked.connect(self.carregar_arquivo)
        self.btn_apagar_valores.clicked.connect(self.apagar_lista_valores)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Conversor arquivo FIXO"))
        self.btn_add_valor.setText(_translate("Form", "Adicionar valor"))
        self.ln_valor.setPlaceholderText(_translate("Form", "Valor"))
        self.ln_inicio.setPlaceholderText(_translate("Form", "Inicio"))
        self.ln_fim.setPlaceholderText(_translate("Form", "Fim"))
        self.btn_processar.setText(_translate("Form", "Processar"))
        self.btn_apagar_valor.setText(_translate("Form", "Apagar valor"))
        self.btn_apagar_valores.setText(_translate("Form", "Apagar valores"))

    def cad_valor(self):

        if self.ln_valor.text() == '' or self.ln_inicio.text() == '' or self.ln_fim.text() == '':
            self.msg_erro.setText("")
            self.msg_erro.setText("é necessário informar um valor!")

        else:
            try:

                self.msg_erro.setText("")

                fatiamento.cad_valores(self.ln_valor.text(), int(self.ln_inicio.text()), int(self.ln_fim.text()))

                self.tv_valores.setColumnCount(1)
                self.tv_valores.setRowCount(20)

                for e, valor in enumerate(fatiamento.listar_valores()):
                    for j in range(0, 1):
                        self.tv_valores.setItem(e, j, QtWidgets.QTableWidgetItem(str(valor)))


            except Exception as err:

                self.msg_erro.setText("Os valores de inicio e fim devem ser números!")

            finally:
                self.ln_valor.setText('')
                self.ln_inicio.setText('')
                self.ln_fim.setText('')

    def gerar_arq(self):

        fatiamento.retorno_fatiamento()

    # função para carregar o arquivo TXT e salvar
    def carregar_arquivo(self):

        if len(fatiamento.dici) > 0:

            try:
                self.msg_erro.setText('')

                endereco = QtWidgets.QFileDialog.getOpenFileName()[0]

                arquivo = list(open(endereco, 'r'))

                fatiamento.retorno_fatiamento(arquivo)

                caminho = QtWidgets.QFileDialog.getSaveFileName()[0]

                with open(caminho + '.txt', 'w') as a:
                    for f in fatiamento.conversao:
                        a.write(f"{f}\n" )



            except Exception as err:
                self.msg_erro.setText('Nenhum arquivo selecionado!')

        else:
            self.msg_erro.setText("Necessário cadastrar um valor!")




    # função para limpara os label da tela
    def limpar_valores(self):
        self.ln_valor.setText('')
        self.ln_inicio.setText('')
        self.ln_fim.setText('')

    def apagar_lista_valores(self):

            fatiamento.apagar_lista_valores()
            self.tv_valores.clear()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
